---
- hosts: localhost
  user: root
  pre_tasks:
    - name: be sure apt cache is updated
      apt: update_cache=yes

  tasks:
    - name: install dependencies
      apt: pkg={{item}} state=present
      with_items:
        - gcc
        - g++
        - make
        - zip
        - unzip
        - mysql-server
        - apache2
        - php
        - php-cli
        - libapache2-mod-php
        - php-gd
        - php-curl
        - php-mysql
        - php-json
        - php-zip
        - php-mcrypt
        - php-gmp
        - php-xml
        - php-mbstring
        - bsdmainutils
        - ntp
        - phpmyadmin
        - libcgroup-dev
        - linuxdoc-tools
        - linuxdoc-tools-text
        - groff
        - texlive-latex-recommended
        - texlive-latex-extra
        - texlive-fonts-recommended
        - texlive-lang-european
        - awscli

    - name: disable default apache2 site
      file: state=absent path=/etc/apache2/sites-enabled/000-default.conf

    - name: copy deployment script
      copy: src=files/deploy_domserver.sh dest=/root/deploy_domserver.sh mode=0755

    - name: do something with ufw
      ufw: logging=off
      tags: ['domjudge-server', 'ufw']

  handlers:
    - name: reload apache2
      command: /usr/sbin/service apache2 graceful
